<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-TO9852C" failures="1" tests="5" name="Personal loan" time="0.123" errors="0" timestamp="23 Aug 2021 19:12:33 GMT">
  <testcase classname="test.day1" name="demo" time="0.018">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at test.day1.demo(day1.java:14)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
  <testcase classname="test.day2" name="demo" time="0.029"/>
  <testcase classname="test.day4" name="LoginAPIhomeloan" time="0.003"/>
  <testcase classname="test.day4" name="Mobileloginhomeloan" time="0.005"/>
  <testcase classname="test.day4" name="Webloginhomeloan" time="0.003"/>
</testsuite> <!-- Personal loan -->
